sudo: false
dist: xenial
script: ./travis.sh
env:
    - GXX=g++-6 CC=gcc-6
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
notifications:
    email:
        on_success: never
before_install:
    - openssl aes-256-cbc -K $encrypted_b6fd0f17b9f3_key -iv $encrypted_b6fd0f17b9f3_iv -in test/tests/backupManager/data/key.key.enc -out test/tests/backupManager/data/key.key -d