sudo: false
env:
    - GXX=g++-9 CC=gcc-9
addons:
    apt:
        sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
        packages:
            - gcc-9
            - g++-9
notifications:
    email:
        on_success: never
before_install:
script: ./travis.sh
dist: xenial
